footprint: [[0.3, 0.3], [0.3, -0.3], [-0.3, -0.3], [-0.3, 0.3]]
transform_tolerance: 0.2

max_obstacle_height: 2.0  # assume something like an arm is mounted on top of the robot
resolution: 0.05

# Obstacle Cost Shaping (http://wiki.ros.org/costmap_2d/hydro/inflation)

obstacle_layer:
  enabled:              true
  max_obstacle_height:  2.0
  origin_z:             0.0
  z_resolution:         0.2
  z_voxels:             8
  unknown_threshold:    15
  mark_threshold:       0
  combination_method:   1
  track_unknown_space:  false    #true needed for disabling global path planning through unknown space
  obstacle_range: 2.5
  raytrace_range: 3.0
  publish_voxel_map: true
  inflation_radius: 0.05
  observation_sources:  pointcloud_laserscan laserscan pointcloud
  laserscan:
    data_type: LaserScan
    topic: /scan
    marking: true
    clearing: true
    min_obstacle_height: 0.01 #scan data's real frame is head but it is broadcasted as base_link.
    max_obstacle_height: 1.0
  pointcloud_laserscan:
    data_type: LaserScan
    topic: /camera/scan
    marking: true
    clearing: true
    min_obstacle_height: 0.01 #scan data's real frame is head but it is broadcasted as base_link.
    max_obstacle_height: 2.0

  pointcloud:
    data_type: PointCloud2
    topic: /camera/depth_registered/points
    marking: true
    clearing: true
    min_obstacle_height: 0.1 #scan data's real frame is head but it is broadcasted as base_link.
    max_obstacle_height: 2.0


  
range_sensor_layer:
  ns: "/cliff_controller"
  clear_threshold:    0.40
  mark_threshold:     0.90
  inflate_cone:  0.0
  clear_on_max_reading: false
  topics: ["/cliff_front_right","/cliff_front_left","/cliff_rear_right","/cliff_rear_left"]

#inflation_layer:
#  enabled:              true
#  cost_scaling_factor:  3.0  # exponential rate at which the obstacle cost drops off (default: 10)
#  inflation_radius:     1.0  # max. distance from an obstacle at which costs are incurred for planning paths.

