
# Obstacle Cost Shaping (http://wiki.ros.org/costmap_2d/hydro/inflation)
robot_radius: 0.18  # distance a circular robot should be clear of the obstacle (kobuki: 0.18)
# footprint: [[x0, y0], [x1, y1], ... [xn, yn]]  # if the robot is not circular

map_type: costmap

always_send_full_costmap: true

plugins:
  - {name: inflation_layer,        type: "costmap_2d::InflationLayer"}
  - {name: obstacle_layer,         type: "costmap_2d::ObstacleLayer"}

obstacle_layer:
  enabled:              true
  combination_method:   1
  track_unknown_space:  false    #true needed for disabling global path planning through unknown space
  obstacle_range: 50.0
  raytrace_range: 5.0
  observation_sources:  laserscan
  laserscan:
    data_type: LaserScan
    topic: /scan_filtered
    marking: true
    clearing: true
    min_obstacle_height: 0.01
    max_obstacle_height: 0.4

 
#cost_scaling_factor and inflation_radius were now moved to the inflation_layer ns
inflation_layer:
  enabled:              true
  cost_scaling_factor:  5.0  # exponential rate at which the obstacle cost drops off (default: 10)
  inflation_radius:     0.5  # max. distance from an obstacle at which costs are incurred for planning paths.

  


