footprint: [[0.13, 0.24], [0.13, -0.24], [-0.37, -0.24], [-0.37, 0.24]]
transform_tolerance: 0.2

#always_send_full_costmap: true
obstacle_layer:
 enabled: true
 obstacle_range: 3.0
 raytrace_range: 3.5
 max_obstacle_height: 0.5
 inflation_radius: 0.10
# track_unknown_space: false
# #publish_voxel_map: true

 combination_method: 1

 observation_sources: scan
 scan: {sensor_frame: base_link, data_type: LaserScan, topic: scan, marking: true, clearing: true, min_obstacle_height: 0.1, max_obstacle_height: 1.0}

range_sensor_layer:
  ns: "/cliff_controller"
  clear_threshold:    0.40
  mark_threshold:     0.90
  inflate_cone:  0.0
  clear_on_max_reading: false
  topics: ["/cliff_front_right","/cliff_front_left","/cliff_rear_right","/cliff_rear_left"]

inflation_layer:
  enabled:              true
  cost_scaling_factor:  3.0  # exponential rate at which the obstacle cost drops off (default: 10)
  inflation_radius:     1.0  # max. distance from an obstacle at which costs are incurred for planning paths.

