global_frame: odom
robot_base_frame: base_link
update_frequency: 10.0
publish_frequency: 10.0

#set if you want the voxel map published
publish_voxel_map: false

#set to true if you want to initialize the costmap from a static map
static_map: false

rolling_window: true
width: 25.0
height: 25.0
resolution: 0.05

footprint_clearing_enabled: true
combination_method: 0
track_unkown_space: false
always_send_full_costmap: true

transform_tolerance: 0.3
obstacle_range: 8.0
raytrace_range: 12.0
robot_radius: 0.45
max_obstacle_height: 0.8
footprint_padding: 0.05
inflation_radius: 1.5
observation_sources: lslidar
realsense: {topic: "d435/depth/color/pointsDISABLED", data_type: PointCloud2, expected_update_rate: 0.1,
  observation_persistence: 0.1, marking: true, clearing: true, max_obstacle_height: 0.9, min_obstacle_height: 0.2, inf_is_valid: true}
lslidar: {topic: "lslidar_point_cloud", data_type: PointCloud2, expected_update_rate: 0.2,
  observation_persistence: 0.1, marking: true, clearing: true, max_obstacle_height: 1.5, min_obstacle_height: 0.2, inf_is_valid: true}
