#!/bin/bash

#
# Load lynx env
#
. /home/lynx/.lynx/setup.sh

LYNX_VERSION=$(cat ${LYNX_PATH}/VERSION)
LYNX_BRANCH=$(git --git-dir ${LYNX_PATH}/.git rev-parse --abbrev-ref HEAD)

[ -r /etc/lsb-release ] && . /etc/lsb-release

if [ -z "$DISTRIB_DESCRIPTION" ] && [ -x /usr/bin/lsb_release ]; then
        # Fall back to using the very slow lsb_release utility
        DISTRIB_DESCRIPTION=$(lsb_release -s -d)
fi


red=$'\e[1;31m'
grn=$'\e[1;32m'
yel=$'\e[1;33m'
blu=$'\e[1;34m'
mag=$'\e[1;35m'
cyn=$'\e[1;36m'
lgr=$'\e[1;90m'
lgr2=$'\e[0;80m'
end=$'\e[0m'

LYNX_SERVICE_STATE=$(systemctl is-active --quiet lynx && echo "${grn}RUNNING${end}" || echo -e "${red}DOWN${end}")

# echo ""
echo -e "${lgr}#########################################################################"
echo -e " ${yel}LYNX ${blu}by Cogniteam ${lgr}\t$(lsb_release -s -d) $(uname -r)"
echo -e   "${lgr}-------------------------------------------------------------------------"
echo -e " ${grn}state: ${LYNX_SERVICE_STATE} ${lgr}|${end} ${grn}version:${end} ${LYNX_VERSION} ${lgr}| ${grn}branch:${end} ${LYNX_BRANCH}"
echo -e   "${lgr}-------------------------------------------------------------------------"
echo -e " ${end}${lgr2}ROS_MASTER_URI=${ROS_MASTER_URI}${end} ${lgr}|${end} ${lgr2}ROS_IP=${ROS_IP}${end}"
echo -e "${lgr}#########################################################################${end}\n"
