local_costmap:
  global_frame: odom
  robot_base_frame: base_footprint
  update_frequency: 10
  publish_frequency: 10
  rolling_window: true
  static_map: false
  width: 4
  height: 4
  #resolution: 0.05
  transform_tolerance: 0.5
  inflation_layer: 
    enabled: true
    inflation_radius: 0.35
    cost_scaling_factor: 3.0


  plugins:
   - {name: obstacle_layer,      type: "costmap_2d::VoxelLayer"}
   - {name: range_sensor_layer,   type: "range_sensor_layer::RangeSensorLayer"}
   - {name: inflation_layer,     type: "costmap_2d::InflationLayer"} 
 
 
